FROM ros:kinetic-perception-jessie

#Workspace to use
RUN mkdir -p root/catkin_ws/src/
RUN /bin/bash -c 'cd /root/catkin_ws'

#Copy code
RUN cd ..
COPY . root/catkin_ws/src/sdbackground

#Launch the compile
RUN /bin/bash -c ' source /opt/ros/kinetic/setup.bash \
        && cd root/catkin_ws\
	&& catkin_make'
